# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7abf1eb4e9f196469a0bcd7bf9e3e4042eaac07dd7cf4d3487ae4a6b0c78a4645fb69e1970c64e56acb75e645c04f7579300ab78c7ccad3f6648c18abffe9f

test:
  secret_key_base: f4cec654fc5448ab51c18674492d7bf3cb88630026829926349fd7d4f3e516d81e790d66d8ef4335affcfe4fa2bf9e8d5bcd553382da9b70e1abcc96ef158158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
